/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.controladores.ControladorProducto;

/**
 *
 * @author Domenica Cañizares
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControladorCliente contCliente;
    private ControladorProducto contProducto;
    
    //cotroladores
    
    //VentanaModificarCliente mod = new VentanaModificarCliente(contCliente);//modificar
    
    
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        contCliente = new ControladorCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jlbTitulo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        crearMenuItem = new javax.swing.JMenuItem();
        buscarMenuItem = new javax.swing.JMenuItem();
        modificarAsMenuItem = new javax.swing.JMenuItem();
        eliminarMenuItem = new javax.swing.JMenuItem();
        imprimirMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        crearPMenuItem = new javax.swing.JMenuItem();
        buscarPMenuItem = new javax.swing.JMenuItem();
        modificarPMenuItem = new javax.swing.JMenuItem();
        eliminarPMenuItem = new javax.swing.JMenuItem();
        listarPMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        crearFMenuItem = new javax.swing.JMenuItem();
        modificarFMenuItem = new javax.swing.JMenuItem();
        buscarFMenuItem = new javax.swing.JMenuItem();
        eliminarFMenuItem = new javax.swing.JMenuItem();
        listarFMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlbTitulo.setText("Factura");
        desktopPane.add(jlbTitulo);
        jlbTitulo.setBounds(130, 20, 160, 40);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cliente");

        crearMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        crearMenuItem.setMnemonic('o');
        crearMenuItem.setText("Crear");
        crearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(crearMenuItem);

        buscarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        buscarMenuItem.setMnemonic('s');
        buscarMenuItem.setText("Buscar");
        buscarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(buscarMenuItem);

        modificarAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        modificarAsMenuItem.setMnemonic('a');
        modificarAsMenuItem.setText("Modificar");
        modificarAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(modificarAsMenuItem);

        eliminarMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        eliminarMenuItem.setMnemonic('x');
        eliminarMenuItem.setText("Eliminar");
        eliminarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(eliminarMenuItem);

        imprimirMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        imprimirMenuItem1.setText("Imprimir");
        imprimirMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(imprimirMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Producto");

        crearPMenuItem.setMnemonic('t');
        crearPMenuItem.setText("Crear Producto");
        crearPMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(crearPMenuItem);

        buscarPMenuItem.setMnemonic('y');
        buscarPMenuItem.setText("Buscar Producto");
        buscarPMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(buscarPMenuItem);

        modificarPMenuItem.setMnemonic('p');
        modificarPMenuItem.setText("Modificar Producto");
        modificarPMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(modificarPMenuItem);

        eliminarPMenuItem.setMnemonic('d');
        eliminarPMenuItem.setText("Eliminar Producto");
        eliminarPMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(eliminarPMenuItem);

        listarPMenuItem.setMnemonic('d');
        listarPMenuItem.setText("Listar Productos");
        listarPMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(listarPMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Factura");

        crearFMenuItem.setMnemonic('t');
        crearFMenuItem.setText("Crear Factura");
        crearFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(crearFMenuItem);

        modificarFMenuItem.setMnemonic('p');
        modificarFMenuItem.setText("Modificar Factura");
        modificarFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarFMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(modificarFMenuItem);

        buscarFMenuItem.setMnemonic('y');
        buscarFMenuItem.setText("Buscar Factura");
        buscarFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(buscarFMenuItem);

        eliminarFMenuItem.setMnemonic('d');
        eliminarFMenuItem.setText("Eliminar Factura");
        eliminarFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(eliminarFMenuItem);

        listarFMenuItem.setMnemonic('d');
        listarFMenuItem.setText("Listar Factura");
        listarFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(listarFMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_eliminarMenuItemActionPerformed

    private void imprimirMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirMenuItem1ActionPerformed
        ListaClientes listar = new ListaClientes(contCliente);//crear
        listar.setVisible(true);
        desktopPane.add(listar);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_imprimirMenuItem1ActionPerformed

    private void crearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMenuItemActionPerformed
        VentanaCrearCliente crear = new VentanaCrearCliente(contCliente);//crear
        crear.setVisible(true);
        desktopPane.add(crear);
        jlbTitulo.setVisible(false);
        
    }//GEN-LAST:event_crearMenuItemActionPerformed

    private void modificarAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAsMenuItemActionPerformed
        
        //mod.setVisible(true);
       // desktopPane.add(mod);
        jlbTitulo.setVisible(false);
        
        
    }//GEN-LAST:event_modificarAsMenuItemActionPerformed

    private void buscarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMenuItemActionPerformed
        VentanaBuscarCliente buscarC = new VentanaBuscarCliente(contCliente);//buscar
        buscarC.setVisible(true);
        desktopPane.add(buscarC);
        jlbTitulo.setVisible(false);
        
    }//GEN-LAST:event_buscarMenuItemActionPerformed

    private void crearPMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPMenuItemActionPerformed
        ProductoCrear crearP = new ProductoCrear(/*contProducto*/);//crear
        crearP.setVisible(true);
        desktopPane.add(crearP);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_crearPMenuItemActionPerformed

    private void crearFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFMenuItemActionPerformed
        CrearFactura listarF = new CrearFactura();//crear
        listarF.setVisible(true);
        desktopPane.add(listarF);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_crearFMenuItemActionPerformed

    private void buscarPMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPMenuItemActionPerformed
        ProductoBuscar buscarP = new ProductoBuscar(/*contProducto*/);//crear
        buscarP.setVisible(true);
        desktopPane.add(buscarP);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_buscarPMenuItemActionPerformed

    private void modificarPMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPMenuItemActionPerformed
        ProductoModificar modP = new ProductoModificar(/*contProducto*/);//crear
        modP.setVisible(true);
        desktopPane.add(modP);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_modificarPMenuItemActionPerformed

    private void eliminarPMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPMenuItemActionPerformed
        ProductoEliminar eliminarP = new ProductoEliminar(/*contProducto*/);//crear
        eliminarP.setVisible(true);
        desktopPane.add(eliminarP);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_eliminarPMenuItemActionPerformed

    private void listarPMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPMenuItemActionPerformed
        ProductoListar listarP = new ProductoListar(/*contProducto*/);//crear
        listarP.setVisible(true);
        desktopPane.add(listarP);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_listarPMenuItemActionPerformed

    private void modificarFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarFMenuItemActionPerformed
        ModificarFactura modF = new ModificarFactura();//modificar
        modF.setVisible(true);
        desktopPane.add(modF);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_modificarFMenuItemActionPerformed

    private void buscarFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFMenuItemActionPerformed
        BuscarFactura buscarF = new BuscarFactura();//buscar
        buscarF.setVisible(true);
        desktopPane.add(buscarF);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_buscarFMenuItemActionPerformed

    private void eliminarFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFMenuItemActionPerformed
        EliminarFactura eliF = new EliminarFactura();//eliminar
        eliF.setVisible(true);
        desktopPane.add(eliF);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_eliminarFMenuItemActionPerformed

    private void listarFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFMenuItemActionPerformed
        ListarFactura listarF = new ListarFactura();//eliminar
        listarF.setVisible(true);
        desktopPane.add(listarF);
        jlbTitulo.setVisible(false);
    }//GEN-LAST:event_listarFMenuItemActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarFMenuItem;
    private javax.swing.JMenuItem buscarMenuItem;
    private javax.swing.JMenuItem buscarPMenuItem;
    private javax.swing.JMenuItem crearFMenuItem;
    private javax.swing.JMenuItem crearMenuItem;
    private javax.swing.JMenuItem crearPMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem eliminarFMenuItem;
    private javax.swing.JMenuItem eliminarMenuItem;
    private javax.swing.JMenuItem eliminarPMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem imprimirMenuItem1;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JMenuItem listarFMenuItem;
    private javax.swing.JMenuItem listarPMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem modificarAsMenuItem;
    private javax.swing.JMenuItem modificarFMenuItem;
    private javax.swing.JMenuItem modificarPMenuItem;
    // End of variables declaration//GEN-END:variables

}
